AssertJ is so cool. I just have to tell somebody about this. Look, I'm testing when my system throws an IOException wrapped in a RuntimeException. Now, JUnit 5 has assertThrows, and it's great. I love it. Here, I'm catching the RuntimeException when I call my method. It returns the exception. I can get the cause. I can check the class. I can check the message. Wonderful. But this is a work of art. I mean, look at this. Assert that exception of type RuntimeException is thrown by my method call with cause exactly instance of IOException with message-containing network problems. I mean, that's just beautiful, man. I'm getting all emotional. Maybe you should watch another video or subscribe to Tales from the Jar side.
